# Generated by Django 5.1 on 2024-10-05 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_receipt"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderplaced",
            name="address",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="app.address",
            ),
        ),
    ]
