# Generated by Django 5.1 on 2024-10-07 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_orderplaced_address"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("shipping_address", models.JSONField()),
                ("order_date", models.DateTimeField()),
                ("total_cost", models.FloatField()),
                ("order_items", models.JSONField()),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.orderplaced",
                    ),
                ),
            ],
        ),
    ]
