# Generated by Django 5.1 on 2024-10-07 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_orderplaced_address"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("shipping_address", models.JSONField()),
                ("order_date", models.DateTimeField()),
                ("total_cost", models.FloatField()),
                ("order_items", models.JSONField()),
                ("txn_id", models.CharField(max_length=255)),
                ("payment_method_type", models.CharField(max_length=50)),
                ("merchant_id", models.CharField(max_length=100)),
                ("txn_uuid", models.CharField(max_length=255)),
                ("gateway", models.CharField(max_length=50)),
                ("card_details", models.JSONField(blank=True, null=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.orderplaced",
                        unique=True,
                    ),
                ),
            ],
        ),
    ]
