# Generated by Django 5.1 on 2024-10-07 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_transaction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="order",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="app.orderplaced"
            ),
        ),
        migrations.DeleteModel(
            name="Receipt",
        ),
    ]
