# Generated by Django 5.1 on 2024-10-07 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_transaction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="app.orderplaced",
                unique=True,
            ),
        ),
    ]
