# Generated by Django 5.1 on 2024-11-04 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_transaction_status_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderplaced",
            name="gateway",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
