# Generated by Django 3.1.5 on 2024-06-26 17:47

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_orderplaced_customer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="product_image",
            field=django_resized.forms.ResizedImageField(
                blank=True,
                crop=None,
                force_format=None,
                keep_meta=True,
                null=True,
                quality=-1,
                scale=None,
                size=[500, 300],
                upload_to="productimg",
            ),
        ),
    ]
