# Generated by Django 5.0.6 on 2024-06-28 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0013_companydetail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="product_image",
            field=models.ImageField(blank=True, null=True, upload_to="productimg"),
        ),
    ]
