# Generated by Django 5.0.6 on 2024-06-29 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0016_productvariation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("M", "Mobile"),
                    ("L", "Laptop"),
                    ("MW", "Men_Wear"),
                    ("WW", "Women_Wear"),
                ],
                max_length=20,
            ),
        ),
    ]
