# Generated by Django 5.0.6 on 2024-08-07 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0019_customer_user_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
